repos:
  - repo: local
    hooks:
      - id: terraform-fmt-recursive
        name: Terraform Format Recursive
        entry: ./terraform-fmt.sh
        language: script
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_validate
        exclude: "^\\.terraform/"
        always_run: true